apiVersion: v1
kind: Service
metadata:
  name: citus-coordinator-service
spec:
  selector:
    app: citus-coordinator
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort
  