apiVersion: apps/v1
kind: Deployment
metadata:
  name: citus-coordinator-deployment
  labels:
    app: citus-coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: citus-coordinator
  template:
    metadata:
      labels:
        app: citus-coordinator
    spec:
      containers:
        - name: citus-coordinator
          image: citusdata/citus
          env:
            - name: POSTGRES_PASSWORD
              value: mypassword
            - name: PGCLUSTER_WORKER_PORT
              value: "5432"
          ports:
            - containerPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: citus-worker-statefulset
spec:
  serviceName: citus-worker-service
  replicas: 2
  selector:
    matchLabels:
      app: citus-worker
  template:
    metadata:
      labels:
        app: citus-worker
    spec:
      containers:
        - name: citus-worker
          image: citusdata/citus
          env:
            - name: POSTGRES_PASSWORD
              value: mypassword
            - name: PGCLUSTER_RESOLVE_WORKERS
              value: "true"
          ports:
            - containerPort: 5432