apiVersion: apps/v1
kind: Deployment
metadata:
  name: citus-deployment
  labels:
    app: citus-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: citus-master
  template:
    metadata:
      labels:
        app: citus-master
    spec:
      containers:
        - name: citus-master
          image: citusdata/citus
          env:
            - name: POSTGRES_PASSWORD
              value: mypassword
